"""update db

Revision ID: bd87c0f129e2
Revises: 011
Create Date: 2026-08-01 17:56:33.299678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd87c0f129e2'
down_revision: Union[str, None] = '011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('learning_goals', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('learning_goals', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', 'ABANDONED', name='goalstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))
    op.alter_column('learning_records', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('learning_records', 'session_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_learning_records_user_input'), table_name='learning_records')
    op.alter_column('llm_settings', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_llm_settings_id'), 'llm_settings', ['id'], unique=False)
    op.alter_column('notes', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('notes', 'session_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_recommendations_user_forecast_created'), table_name='recommendations')
    op.create_index(op.f('ix_recommendations_forecast_date'), 'recommendations', ['forecast_date'], unique=False)
    op.alter_column('reminders', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('reminders', 'session_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('study_sessions', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('study_sessions', 'goal_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('study_sessions', 'difficulty',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty'),
               existing_nullable=True)
    op.alter_column('tasks', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('tasks', 'session_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('tasks', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('study_sessions', 'difficulty',
               existing_type=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('study_sessions', 'goal_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('study_sessions', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('reminders', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('reminders', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_recommendations_forecast_date'), table_name='recommendations')
    op.create_index(op.f('ix_recommendations_user_forecast_created'), 'recommendations', ['user_id', 'forecast_date', 'created_at'], unique=False)
    op.alter_column('notes', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('notes', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_llm_settings_id'), table_name='llm_settings')
    op.alter_column('llm_settings', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_learning_records_user_input'), 'learning_records', ['user_input'], unique=False)
    op.alter_column('learning_records', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('learning_records', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('learning_goals', 'status',
               existing_type=sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', 'ABANDONED', name='goalstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))
    op.alter_column('learning_goals', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###


